### ISSUE TITLE
pathElementsFromFile damages file name if it contains the root path

### ISSUE THREAD

**Issue by dandew** [atomist/artifact-source#29]
I was puzzled by the following error:

    .atomist/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:16 Error: Module not found: ./code-gen

After step debugging I realized the issue comes from the fact this code is checked out under `/code` by our CI server:

![screen shot 2017-06-05 at 17 02 09](https://cloud.githubusercontent.com/assets/14323673/26809363/0b3ec162-4a19-11e7-9c0a-0db00d167052.png)

As you can see above, `pathElementsFromFile` has removed `/code` from the file name, thus changing `../compiler/code-gen.js` into `../compiler-gen.js`, which is nonsensical and fails the `rug` evaluation.

**Comment by alankstewart** [comment]
@dandew This should be fixed now in release 1.0.0-m.4

**Comment by kipz** [comment]
So @dandew, you can either wait until the next release of Rug, or use the latest timestamped version:
https://atomist.jfrog.io/atomist/list/libs-dev/com/atomist/rug/1.0.0-20170607055624/

If you use the CLI, you'll need to make sure that repo to your cli.yml.

**Comment by dandew** [comment]
@kipz @alankstewart Happy to confirm that the bug is gone in `1.0.0-20170607055624` 👍 :shipit:
