### ISSUE TITLE
GitHub Artifactor Source issue with editing new file

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/artifact-source#36]
- we're testing a terraform Editor and having a problem with what appears to be:

1.  create new file
2.  edit this newly created file
3.  commit

**Comment by alankstewart** [comment]
@slimslenderslacks It would be preferable if I can reproduce this in a unit test in artifact-source.

**Comment by cdupuis** [comment]
Using the steps above you should be able to recreate the issue. 

clone repo
Add new empty file
Edit the new file
Edit it again
Attempt to create a PR

**Comment by alankstewart** [comment]
@slimslenderslacks @cdupuis please try 1.0.0-m.6

**Comment by cdupuis** [comment]
on it, thanks.

**Comment by alankstewart** [comment]
@slimslenderslacks @cdupuis @Lawouach Problem found: GitHub is sending back  a 422 Unprocessable entity response with the message `{"message":"tree.path contains a malformed path component","documentation_url":"https://developer.github.com/v3/git/trees/#create-a-tree"}`
This is because the path contained a leading `./`, e.g. `./terraform`. One option is for artefact sources to strip this leading path out.

**Comment by alankstewart** [comment]
After speaking with @johnsonr I will strip out the leading relative path when artefact-sources are created

**Comment by Lawouach** [comment]
Well happy you found the issue @alankstewart, clearly something that wasn't (couldn't be) picked up when I ran locally unfortunately. Sorry it took so much of your weekend.

**Comment by ddgenome** [comment]
How does artifact source currently deal with absolute paths, i.e., paths starting with a forward slash, e.g., `/foo`, relative paths starting with relative directories, e.g., `./foo` and `../foo`, and other relative paths, e.g., `foo`?

It might be best to just have a convention, e.g., all paths must be absolute and are rooted at the root of the project or all paths are relative and cannot begin with relative directories, and just document that. If Rugs want to be more permissive, they can be responsible for sanitizing the input.

Whatever the path forward, we should make sure that any error message is clear and surface to the Rug and user.

**Comment by alankstewart** [comment]
Paths starting with a forward slash have not been allowed since this repo was created. As of 1.0.0-m.11, no relative path elements are allowed. An exception is thrown with this message. When 1.0.0-m.13 is released, no parent path elements will be allowed either, e.g. `src/test/../foo.bar`
