### ISSUE TITLE
Add Squash and Merge for PR

### ISSUE THREAD

**Issue by cdupuis** [atomist/artifact-source#44]

**Comment by alankstewart** [comment]
Squash is default for the mergePullRequest method

**Comment by cdupuis** [comment]
Ah, cool. Is that new?

In that case we need the non-squash to be available. Is that too?

**Comment by alankstewart** [comment]
Only new since github-lib was removed, i.e. 1.0.0-m.14. Valid values to the `mergePullRequest`method's `mergeMethod` field are `squash` (default if not specified), `merge`, and `rebase`, as per https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button
