### ISSUE TITLE
.atomist/ignore not properly rooting paths

### ISSUE THREAD

**Issue by ddgenome** [atomist/artifact-source#45]
The expected behavior of the `.atomist/ignore` file is to root absolute paths at the project root. This does not appear to be happening per Michael Duergner in atomist-community.

https://atomist-community.slack.com/archives/C29DX2W07/p1501592971771131

If the following line appears in `.atomist/ignore`,

```
/classes/
```

We expect that a directory named `classes` at the root of the project, i.e., the same level as the `.git` and `.atomist` directories, would be excluded from the archive.

**Comment by alankstewart** [comment]
Should be fixed in master now

**Comment by alankstewart** [comment]
Fixed in 1.0.0-m.16
