### ISSUE TITLE
methods using httpRequestOption are not retried

### ISSUE THREAD

**Issue by ddgenome** [atomist/artifact-source#46]
Methods like `GitHubServices.getBranch` are using `retry` but are not retried because they are using `httpRequestOption` which catches exceptions and returns `None`.

Similarly, the GitHubServices.createRepository method uses the construct `httpRequestOption().getOrElse(httpRequest())`, so the API call in the `httpRequestOption` does not get retried.

The retry logic needs to be smarter. Perhaps create `httpRequestOptionWithRetry` and `httpRequestWithRetry` and modify code accordingly, e.g., do not retry around that.

**Comment by alankstewart** [comment]
Fixed in 1.0.0-m.17
