### ISSUE TITLE
Consider throwing exceptions and allowing consumer to handle as required

### ISSUE THREAD

**Issue by kipz** [atomist/artifact-source#47]
https://github.com/atomist/artifact-source/blob/master/src/main/scala/com/atomist/source/git/GitRepositoryCloner.scala#L39

This munging of the exception makes it hard to debug and otherwise handle errors appropriately. I feel like this should be handled by the user of the library.

**Comment by alankstewart** [comment]
Agreed. Will throw ArtifactSourceException and return simple File object in happy case. Test code is much simpler now as result

**Comment by alankstewart** [comment]
Should be fixed in 1.0.0-m.17

**Comment by alankstewart** [comment]
Released also as part of rug 1.0.0-m.6
