### ISSUE TITLE
Model access permissions in artifacts (file/dir)

### ISSUE THREAD

**Issue by kipz** [atomist/artifact-source#6]
Original issue from @jessitron:

https://github.com/atomist/rug/issues/13

**Comment by alankstewart** [comment]
@kipz We already have a 'mode' field on FileArtifact which is used to store the file permissions in Octal format, e.g. 100755 for executable files. Is this not enough? This was added some time ago when Adrian found that creating a repo from a template was losing executable permissions on shell scripts.

**Comment by kipz** [comment]
Ah, OK. I totally missed that. Sorry for the noise. Issue must be elsewhere.
