### ISSUE TITLE
Use .atomistignore over .gitignore (if present)

### ISSUE THREAD

**Issue by kipz** [atomist/artifact-source#8]
We need to be able to ignore some files for git checkin, but allow them for adding to an archive. For example, node_modules.

Override mechanics should probably look like .npmignore:

https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by alankstewart** [comment]
@kipz @cd I've add the .atomistignore functionality as close possible as what the .npmignore doc says above.
As per .npmignore, it will consider all .atomistignore files found in the root of the project and its subdirectories. Unlike .gitignore which always ignores directories like ".git" I also added .git and a few other artefacts that are ignored by default - some of which are listed in the .npmignore doc (e.g. .git, .svn, .idea, *.iml, and eclipse project hidden files. But if you don't want these added, let me know.

If a .atomistignore file is not found, then the global .gitgnore file is read along with any .gitignore files in the project root and subdirectories.

Note, like .npmignore, if a .atomistignore file is present, even if empty, it will override anything in .gitignore files (if present)

Available in release 0.11.0

**Comment by kipz** [comment]
Great! :)

**Comment by alankstewart** [comment]
artifact-source now uses JGit to process .gitignore files, and also supports a `.atomist/ignore` file to allow ignoring files under .atomist or to negate patterns matched in .gitignore processing
